worker_processes    auto;

events {
    worker_connections  512;
}

http {
    include     /etc/nginx/mime.types;

    access_log  /var/log/nginx/access.log;
    error_log   /var/log/nginx/error.log;

    proxy_buffering         on;
    proxy_buffer_size       256k;
    proxy_buffers           4   256k;

    upstream corrector {
        server  news.corrector:8000;
    }

    upstream classifier {
        server  news.classifier:8000;
    }

    upstream summarizer {
        server  news.summarizer:8000;
    }

    upstream oauth2-service {
        server  news.oauth2:4180;
    }

    ### === CORS ORIGINS ===
    map $http_origin $allow_origin {
        default "*";
        "~^http://localhost(:[0-9]+)?$" $http_origin;
    }

    server {
        listen  80;

        ### === CORS PARAMS ===
        add_header  'Access-Control-Allow-Origin'   $allow_origin   always;
        add_header  'Access-Control-Allow-Methods'  'GET, POST, OPTIONS, PUT, DELETE'   always;
        add_header  'Access-Control-Allow-Headers'  'Authorization,Content-Type,Accept,Origin,User-Agent,X-Requested-With'  always;
        add_header  'Access-Control-Max-Age'        1728000;
        add_header  'Access-Control-Allow-Credentials' 'true' always;

        ### === AUTHENTICATION & AUTHORIZATION FLOW ===
        location /oauth2/ {
            proxy_pass          http://oauth2-service;
            proxy_set_header    Host                        $proxy_host;
            proxy_set_header    X-Real-IP                   $remote_addr;
            proxy_set_header    X-Auth-Request-Uri          $scheme://$host$request_uri;
        }

        location = /oauth2/sign_out {
            proxy_pass          http://oauth2-service/oauth2/sign_out?rd=http://news-keycloak-alias.127.0.0.1.nip.io:8000/realms/news-keycloak-realm/protocol/openid-connect/logout;
            proxy_set_header    Host                        $proxy_host;
            proxy_set_header    X-Real-IP                   $remote_addr;
        }

        location = /oauth2/auth {
            proxy_pass          http://oauth2-service/oauth2/auth;
            proxy_set_header    Host                        $proxy_host;
            proxy_set_header    X-Real-IP                   $remote_addr;
            proxy_set_header    X-Forwarded-Uri             $request_uri;
            proxy_set_header    Content-Length              "";
            proxy_pass_request_body                         off;
        }

        ### === API FLOW ===
        location /public/api/ {

            limit_except OPTIONS GET {
                deny    all;
            }

            if ($request_method = 'OPTIONS') {
                return 204;
            }

            rewrite ^/public/api/(.*) /api/$1 break;

            proxy_pass  http://news.server:8000;
        }

        location /api/ {
            
            if ($request_method = 'OPTIONS') {
                return 204;
            }

            auth_request     /oauth2/auth;

            proxy_pass  http://news.server:8000;
        }

        location ~ ^/ai/(?<target>classifier|corrector|summarizer)$ {
            
            if ($request_method = 'OPTIONS') {
                return 204;
            }

            auth_request     /oauth2/auth;

            proxy_pass              http://$target/query;
            proxy_read_timeout      300s;
            proxy_connect_timeout   300s;
            proxy_send_timeout      300s;
        }
    }
}